/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module Sumador_8bits (
  input [7:0] Va,
  input [7:0] Vb,
  output [7:0] Out
);
  // Suma
  DIG_Add #(
    .Bits(8)
  )
  DIG_Add_i0 (
    .a( Va ),
    .b( Vb ),
    .c_i( 1'b0 ),
    .s( Out )
  );
endmodule
